'''
・10をnumで割った時の結果を出力しましょう
・0で割った（割れない）場合に「エラー」と出力しましょう
'''

try:
    num = 0
    print(10 / num)
except:
    print('エラー')
